import streamlit as st
import numpy as np
import pickle
import os
from tensorflow.keras.models import load_model
from src.utils import get_linguistic_features, preprocess_text

# Configuration
MAX_SEQ_LENGTH = 250
MODEL_PATH = 'models/checkorigin_model.h5'
TOKENIZER_PATH = 'models/tokenizer.pickle'

st.set_page_config(
    page_title="CheckOrigin | AI Text Detector",
    page_icon="🔍",
    layout="centered"
)

# Custom CSS for research feel
st.markdown("""
    <style>
    .main {
        background-color: #f8f9fa;
    }
    .stButton>button {
        width: 100%;
        border-radius: 5px;
        height: 3em;
        background-color: #007bff;
        color: white;
    }
    .result-box {
        padding: 20px;
        border-radius: 10px;
        text-align: center;
        margin-top: 20px;
    }
    .ai-result {
        background-color: #ffebee;
        color: #c62828;
        border: 2px solid #ef9a9a;
    }
    .human-result {
        background-color: #e8f5e9;
        color: #2e7d32;
        border: 2px solid #a5d6a7;
    }
    </style>
    """, unsafe_allow_html=True)

@st.cache_resource
def load_resources():
    if not os.path.exists(MODEL_PATH) or not os.path.exists(TOKENIZER_PATH):
        return None, None
    
    model = load_model(MODEL_PATH)
    with open(TOKENIZER_PATH, 'rb') as handle:
        tokenizer = pickle.load(handle)
    return model, tokenizer

def main():
    st.title("🔍 CheckOrigin")
    st.subheader("Neural Hybrid Model for AI Text Identification")
    st.write("Enter the text below to determine if it was generated by an AI algorithm or written by a human.")

    model, tokenizer = load_resources()

    if model is None:
        st.error("Error: Model or Tokenizer not found. Please run `train.py` first.")
        return

    user_input = st.text_area("Analyze Text", height=300, placeholder="Paste the text here...")

    if st.button("Run Analysis"):
        if user_input.strip() == "":
            st.warning("Please enter some text to classify.")
        else:
            with st.spinner("Analyzing linguistic patterns..."):
                # Determine expected linguistic feature count from model
                try:
                    num_ling_features = model.input[1].shape[1]
                except:
                    num_ling_features = 2 # Fallback to original
                
                # Preprocess
                padded_seq = preprocess_text(user_input, tokenizer, MAX_SEQ_LENGTH)
                ling_features = get_linguistic_features(user_input, num_features=num_ling_features).reshape(1, num_ling_features)
                
                # Predict
                prediction = model.predict([padded_seq, ling_features])[0][0]
                
                # Display Results
                st.divider()
                st.subheader("Analysis Findings")
                
                confidence = prediction if prediction > 0.5 else 1 - prediction
                
                if prediction >= 0.5:
                    st.markdown(f"""
                        <div class="result-box ai-result">
                            <h3>Probability: AI Generated</h3>
                            <p>Confidence Score: {confidence*100:.2f}%</p>
                        </div>
                        """, unsafe_allow_html=True)
                else:
                    st.markdown(f"""
                        <div class="result-box human-result">
                            <h3>Probability: Human Written</h3>
                            <p>Confidence Score: {confidence*100:.2f}%</p>
                        </div>
                        """, unsafe_allow_html=True)
                
                with st.expander("Technical Metrics"):
                    col1, col2, col3 = st.columns(3)
                    words = user_input.split()
                    col1.metric("Word Count", len(words))
                    col2.metric("Avg Word Length", f"{np.mean([len(w) for w in words]):.2f}" if words else 0)
                    col3.metric("Lexical Diversity", f"{len(set(words))/len(words):.2f}" if words else 0)

    st.sidebar.title("About CheckOrigin")
    st.sidebar.info("""
        CheckOrigin uses a dual-path neural network:
        1. **CNN Path**: Analyzes token sequences for semantic consistency.
        2. **MLP Path**: Evaluates statistical linguistic markers.
        
        The model identifies subtle patterns that distinguish human creativity from algorithmic predictability.
    """)
    st.sidebar.caption("Project developed for Research Integrity.")

if __name__ == "__main__":
    main()
