import streamlit as st
import numpy as np
import os
import onnxruntime as ort

from src.tokenizer_compat import load_tokenizer
from src.utils import get_linguistic_features, preprocess_text

# Configuration
DEFAULT_MAX_SEQ_LENGTH = 150
MODEL_PATH = 'models/checkorigin_model.onnx'
TOKENIZER_PATH = 'models/tokenizer.pickle'
MIN_WORDS_FOR_CLASSIFICATION = 30
SHORT_TEXT_AI_THRESHOLD = 0.8

st.set_page_config(
    page_title="CheckOrigin | AI Text Detector",
    page_icon="🔍",
    layout="centered"
)

# Custom CSS for research feel
st.markdown("""
    <style>
    .main {
        background-color: #f8f9fa;
    }
    .stButton>button {
        width: 100%;
        border-radius: 5px;
        height: 3em;
        background-color: #007bff;
        color: white;
    }
    .result-box {
        padding: 20px;
        border-radius: 10px;
        text-align: center;
        margin-top: 20px;
    }
    .ai-result {
        background-color: #ffebee;
        color: #c62828;
        border: 2px solid #ef9a9a;
    }
    .human-result {
        background-color: #e8f5e9;
        color: #2e7d32;
        border: 2px solid #a5d6a7;
    }
    .uncertain-result {
        background-color: #fff8e1;
        color: #8a5a00;
        border: 2px solid #ffcc80;
    }
    </style>
    """, unsafe_allow_html=True)

@st.cache_resource
def load_resources():
    if not os.path.exists(MODEL_PATH) or not os.path.exists(TOKENIZER_PATH):
        return None, None, None, None
    
    session = ort.InferenceSession(MODEL_PATH)
    tokenizer = load_tokenizer(TOKENIZER_PATH)

    max_seq_length = get_static_dimension(session.get_inputs()[0].shape[1], DEFAULT_MAX_SEQ_LENGTH)
    num_ling_features = get_static_dimension(session.get_inputs()[1].shape[1], 2)
    return session, tokenizer, max_seq_length, num_ling_features

def get_static_dimension(value, fallback):
    if isinstance(value, int) and value > 0:
        return value
    return fallback

def main():
    st.title("🔍 CheckOrigin")
    st.subheader("Neural Hybrid Model for AI Text Identification")
    st.write("Enter the text below to determine if it was generated by an AI algorithm or written by a human.")

    model, tokenizer, max_seq_length, num_ling_features = load_resources()

    if model is None:
        st.error("Error: Model or Tokenizer not found. Please run `train.py` first.")
        return

    user_input = st.text_area("Analyze Text", height=300, placeholder="Paste the text here...")

    if st.button("Run Analysis"):
        if user_input.strip() == "":
            st.warning("Please enter some text to classify.")
        else:
            with st.spinner("Analyzing linguistic patterns..."):
                # Preprocess
                padded_seq = preprocess_text(user_input, tokenizer, max_seq_length)
                ling_features = get_linguistic_features(user_input, num_features=num_ling_features).reshape(1, num_ling_features)
                
                # Predict
                input_name_1 = model.get_inputs()[0].name
                input_name_2 = model.get_inputs()[1].name
                output_name = model.get_outputs()[0].name
                
                padded_seq_onnx = padded_seq.astype(np.int32)
                ling_features_onnx = ling_features.astype(np.float32)
                
                outputs = model.run([output_name], {input_name_1: padded_seq_onnx, input_name_2: ling_features_onnx})
                prediction = float(outputs[0][0][0])
                
                # Display Results
                st.divider()
                st.subheader("Analysis Findings")
                
                words = user_input.split()
                ai_probability = prediction * 100
                confidence = prediction if prediction > 0.5 else 1 - prediction
                
                if len(words) < MIN_WORDS_FOR_CLASSIFICATION and prediction < SHORT_TEXT_AI_THRESHOLD:
                    st.markdown(f"""
                        <div class="result-box uncertain-result">
                            <h3>Insufficient Text for Reliable Classification</h3>
                            <p>AI Probability: {ai_probability:.2f}%</p>
                            <p>Enter at least {MIN_WORDS_FOR_CLASSIFICATION} words unless the AI signal is strong.</p>
                        </div>
                        """, unsafe_allow_html=True)
                elif prediction >= 0.5:
                    st.markdown(f"""
                        <div class="result-box ai-result">
                            <h3>Probability: AI Generated</h3>
                            <p>AI Probability: {ai_probability:.2f}%</p>
                            <p>Confidence Score: {confidence*100:.2f}%</p>
                        </div>
                        """, unsafe_allow_html=True)
                else:
                    st.markdown(f"""
                        <div class="result-box human-result">
                            <h3>Probability: Human Written</h3>
                            <p>AI Probability: {ai_probability:.2f}%</p>
                            <p>Confidence Score: {confidence*100:.2f}%</p>
                        </div>
                        """, unsafe_allow_html=True)
                
                with st.expander("Technical Metrics"):
                    col1, col2, col3 = st.columns(3)
                    col1.metric("Word Count", len(words))
                    col2.metric("Avg Word Length", f"{np.mean([len(w) for w in words]):.2f}" if words else 0)
                    col3.metric("Lexical Diversity", f"{len(set(words))/len(words):.2f}" if words else 0)

    st.sidebar.title("About CheckOrigin")
    st.sidebar.info("""
        CheckOrigin uses a dual-path neural network:
        1. **CNN Path**: Analyzes token sequences for semantic consistency.
        2. **MLP Path**: Evaluates statistical linguistic markers.
        
        The model identifies subtle patterns that distinguish human creativity from algorithmic predictability.
    """)
    st.sidebar.caption("Project developed for Research Integrity.")

if __name__ == "__main__":
    main()
